URL_SERVICE = "https://cnt-59fea874-fec7-4f52-b224-f42247a9813f.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
KIT_MODEL_PATH = "/api/db/resources/kit_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_KIT_PATH = "/api/v1/kits"
